m4_error: fix missing va_end
Most va_end implementations are no-ops, so it probably didn't
affect many people, but POSIX requires all va_start to be
matched with va_end for the rare platform where va_end is not
a no-op.  Detected by Coverity.

* src/m4.c (m4_error, m4_error_at_line): Add missing va_end.

Signed-off-by: Eric Blake <eblake@redhat.com>