maint: update gnulib and fix build failures
I got failures when trying to bootstrap:

bootstrap: getting translations into po/.reference for m4...
receiving incremental file list
rsync: change_dir "/latest/m4" (in tp) failed: No such file or directory (2)

since m4-1.4 has no translation files, and the translation project
dropped the stale .po files for the unreleased 1.9 development branch.

Once that was fixed, I also got compilation failures, from an
incomplete update to the gnulib execute module:

builtin.c: In function 'm4_syscmd':
builtin.c:968:44: error: passing argument 3 of 'execute' from incompatible pointer type [-Werror=incompatible-pointer-types]
  968 |   status = execute (ARG (0), SYSCMD_SHELL, prog_args, NULL, false,
      |                                            ^~~~~~~~~
      |                                            |
      |                                            const char **

Fixes: 4e5c2c0157

* gnulib: Update to latest.
* bootstrap.conf (copyright_holder): Silence bootstrap warning.
(m4_bootstrap_options_prep): Turn off po update.